- internal/core/commands/run_test_signal.go
> Fix issue with unmarshall value

- internal/core/commands/run_test_signal.go
- locallog with more context
- continue instead of return when within loop
> Tweaks to process signal - continue, logging

- charts/vehicle-signal-decoding/values.yaml
- internal/api/api.go
> turn on ingress in dev, fix health endpoint

- internal/controllers/device_config_controller_test.go
- internal/infrastructure/db/migrations/20230911144359_enums_defaults.sql
- internal/infrastructure/db/models/boil_types.go
- internal/infrastructure/db/models/pid_configs.go
> add some defaults, use enum for protocol

- internal/controllers/device_config_controller.go
> parent template for pids endpoint

- internal/core/services/user_device_service.go
> ethAddr string to bytes

- internal/controllers/device_config_controller.go
- internal/controllers/device_config_controller_test.go
> Fix hex to decimal encoding

- internal/core/queries/get_template_by_name.go
> added parent template name in get

- internal/controllers/device_config_controller.go
- internal/core/commands/create_pid.go
- internal/core/common/constants.go
- internal/core/common/utils.go
- internal/core/common/utils_test.go
- seed.sql
> SM-317 formula type precautions

- charts/vehicle-signal-decoding/values-prod.yaml
- charts/vehicle-signal-decoding/values.yaml
- go.mod
- go.sum
- internal/api/api.go
- internal/config/settings.go
- internal/controllers/device_config_controller.go
- internal/controllers/device_config_controller_test.go
- internal/core/appmodels/templates.go
- internal/core/services/device_template_service.go
- internal/core/services/mocks/device_template_service_mock.go
- internal/core/services/mocks/user_device_service_mock.go
- internal/core/services/user_device_service.go
- internal/middleware/owner/owner.go
- internal/middleware/owner/owner_test.go
- internal/test/helpers.go
> SM-489 ud owner auth implemented for status patch

- internal/api/api.go
- internal/middleware/owner/owner.go
- internal/middleware/owner/owner_test.go
- update middleware owner to support device ethAddr in path
> SM-489 implement device eth address owner middleware

- internal/controllers/device_config_controller.go
- internal/controllers/device_config_controller_test.go
> SM-516 rework logic so we always return if we find something

- internal/api/api.go
- internal/core/services/user_device_service.go
- internal/middleware/owner/owner.go
> SM-756 wrap some errors, do not close connection to early

- internal/controllers/device_config_controller.go
- internal/controllers/device_config_controller_test.go
- internal/core/services/device_template_service.go
- internal/core/services/mocks/device_template_service_mock.go
- internal/infrastructure/db/migrations/20240428104728_aftermarket_fkey.sql
- internal/infrastructure/db/models/aftermarket_device_to_template.go
- internal/infrastructure/db/models/dbc_codes.go
- internal/infrastructure/db/models/dbc_files.go
- internal/infrastructure/db/models/device_settings.go
- internal/infrastructure/db/models/device_template_status.go
- internal/infrastructure/db/models/jobs.go
- internal/infrastructure/db/models/pid_configs.go
- internal/infrastructure/db/models/psql_upsert.go
- internal/infrastructure/db/models/template_device_definitions.go
- internal/infrastructure/db/models/template_vehicles.go
- internal/infrastructure/db/models/templates.go
- internal/infrastructure/db/models/test_signals.go
> SM-790 handle logic for Direct Device to template config

- .github/workflows/lint.yml
- internal/controllers/device_config_controller.go
- internal/controllers/device_config_controller_test.go
- internal/core/services/device_template_service.go
- internal/core/services/device_template_service_test.go
- internal/core/services/mocks/device_template_service_mock.go
> tighter matching for MMY, add strategy used to resolve tmpl

- .gitignore
- .idea/vehicle-signal-decoding.iml
- internal/controllers/device_config_controller.go
- internal/core/appmodels/templates.go
- pkg/grpc/hardware_v1.pb.go
- pkg/grpc/hardware_v1.proto
- added LocationFrequencySecs setting
> SM-686: Send location every Configurable X seconds, as low as 1/sec

- internal/api/grpc_server.go
- internal/controllers/device_config_controller.go
- internal/controllers/device_config_controller_test.go
> SM-852 - Vehicle signal decoding fix pull pids

- internal/controllers/device_config_controller_test.go
- internal/core/services/device_template_service.go
- internal/core/services/device_template_service_test.go
> SM-870 fix bug where grabbing tmpl by make is too greedy

- internal/api/api.go
- just minor change to test if Argo will sync with latests commit
> minor change to test if Argo will sync with latests commit

- internal/infrastructure/db/migrations/20240916220326_tmpl_update_cascade.sql
- need flexibility to be able to change template names
> cascade on update

- internal/api/vehicle_template_service.go
- internal/controllers/device_config_controller.go
- internal/core/queries/get_pid_config_all.go
- if template has parents, get their dbc files too and return them
> meld all parent dbc files if any

- go.mod
- go.sum
- internal/controllers/device_config_controller.go
- internal/controllers/device_config_controller_test.go
> update device definitions dep

- docker-compose.yml
- internal/infrastructure/dbtest/test_helper.go
> Bump Postgres to 16.6
